services:
  postgres:
    image: postgres:15-alpine
    container_name: journal-db
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_password
    ports:
      - "5433:5432"  # Use port 5433 on host to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U journal_user -d journal"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
